# Generated by Django 4.1.3 on 2023-01-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IclickMain', '0002_projectdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectDetails',
        ),
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
