# Generated by Django 4.1.3 on 2023-01-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IclickMain', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='project_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='stdid',
            field=models.CharField(max_length=50),
        ),
    ]
