# Generated by Django 4.1.3 on 2023-01-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IclickMain', '0005_alter_projectdetails_project_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_reviews',
            fields=[
                ('revid', models.IntegerField(primary_key=True, serialize=False)),
                ('revName', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
