# Generated by Django 4.1.3 on 2023-01-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IclickMain', '0006_project_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='disc',
            field=models.CharField(max_length=2000),
        ),
    ]
