# Generated by Django 4.1.3 on 2023-01-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IclickMain', '0009_alter_project_reviews_projectid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_reviews',
            name='revid',
        ),
        migrations.AlterField(
            model_name='project_reviews',
            name='projectid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
