# Generated by Django 4.1.3 on 2023-01-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IclickMain', '0010_remove_project_reviews_revid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_reviews',
            name='review',
            field=models.CharField(max_length=500),
        ),
    ]
