# Generated by Django 4.1.3 on 2023-01-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IclickMain', '0011_alter_project_reviews_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_reviews',
            name='projectid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project_reviews',
            name='review',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
