# Generated by Django 4.1.3 on 2023-01-29 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IclickMain', '0012_alter_project_reviews_projectid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project_reviews',
        ),
        migrations.DeleteModel(
            name='ProjectDetails',
        ),
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
