# Generated by Django 4.1.3 on 2023-01-29 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IclickMain', '0013_delete_project_reviews_delete_projectdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('member1', models.CharField(max_length=200)),
                ('member1_rol', models.CharField(max_length=200)),
                ('member2', models.CharField(max_length=200)),
                ('member2_rol', models.CharField(max_length=200)),
                ('member3', models.CharField(max_length=200)),
                ('member3_rol', models.CharField(max_length=200)),
                ('dept', models.CharField(max_length=30)),
                ('member1_pic', models.ImageField(upload_to='project_images/')),
                ('member2_pic', models.ImageField(upload_to='project_images/')),
                ('member3_pic', models.ImageField(upload_to='project_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewersDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('qualif', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='reviewers_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewers_project', to='IclickMain.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorDetails',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('qualif', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='supervisors_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_project', to='IclickMain.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.TextField()),
                ('rating1', models.IntegerField()),
                ('rating2', models.IntegerField()),
                ('rating3', models.IntegerField()),
                ('rating4', models.IntegerField()),
                ('t_rating', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_project', to='IclickMain.projectdetails')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reviewer', to='IclickMain.reviewersdetails')),
            ],
        ),
    ]
