# Generated by Django 4.1.3 on 2023-01-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IclickMain', '0014_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='member1_pic',
            field=models.ImageField(upload_to='media/project_images/'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='member2_pic',
            field=models.ImageField(upload_to='media/project_images/'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='member3_pic',
            field=models.ImageField(upload_to='media/project_images/'),
        ),
        migrations.AlterField(
            model_name='reviewersdetails',
            name='picture',
            field=models.ImageField(upload_to='media/reviewers_images/'),
        ),
        migrations.AlterField(
            model_name='supervisordetails',
            name='picture',
            field=models.ImageField(upload_to='media/supervisors_images/'),
        ),
    ]
