# Generated by Django 4.1.3 on 2023-01-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IclickMain', '0015_alter_projectdetails_member1_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewersdetails',
            name='project',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='reviewersdetails',
            name='reviews',
            field=models.ManyToManyField(related_name='reviewers', to='IclickMain.reviews'),
        ),
        migrations.AlterField(
            model_name='reviewersdetails',
            name='picture',
            field=models.ImageField(upload_to='reviewers_images/'),
        ),
    ]
