# Generated by Django 4.1.3 on 2023-01-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IclickMain', '0016_remove_reviewersdetails_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewersdetails',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, related_name='reviewers', to='IclickMain.reviews'),
        ),
    ]
