# Generated by Django 4.1.3 on 2023-01-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IclickMain', '0017_alter_reviewersdetails_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewersdetails',
            name='picture',
            field=models.ImageField(upload_to='media/reviewers_images/'),
        ),
    ]
