# Generated by Django 4.1.3 on 2023-01-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IclickMain', '0018_alter_reviewersdetails_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='t_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
