# Generated by Django 4.1.3 on 2023-01-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IclickMain', '0019_alter_reviews_t_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewersdetails',
            name='reviews',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
