# Generated by Django 4.1.3 on 2023-01-29 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IclickMain', '0020_remove_reviewersdetails_reviews_delete_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.TextField()),
                ('rating1', models.IntegerField()),
                ('rating2', models.IntegerField()),
                ('rating3', models.IntegerField()),
                ('rating4', models.IntegerField()),
                ('t_rating', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_project', to='IclickMain.projectdetails')),
            ],
        ),
        migrations.AddField(
            model_name='reviewersdetails',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, related_name='reviewers', to='IclickMain.reviews'),
        ),
    ]
