# Generated by Django 4.1.3 on 2023-01-29 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IclickMain', '0021_reviews_reviewersdetails_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_project', to='IclickMain.projectdetails'),
        ),
    ]
