# Generated by Django 4.1.3 on 2023-01-30 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IclickMain', '0022_alter_reviews_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisordetails',
            name='project',
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_project', to='IclickMain.supervisordetails'),
        ),
        migrations.AlterField(
            model_name='reviewersdetails',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/reviewers_images/'),
        ),
        migrations.AlterField(
            model_name='reviewersdetails',
            name='qualif',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
