# Generated by Django 4.1.3 on 2023-01-30 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IclickMain', '0023_remove_supervisordetails_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewersdetails',
            name='reviews',
        ),
        migrations.AddField(
            model_name='reviews',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='IclickMain.reviewersdetails'),
        ),
    ]
