# Generated by Django 4.1.3 on 2023-01-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IclickMain', '0024_remove_reviewersdetails_reviews_reviews_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='dept',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='member1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='member1_rol',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='member2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='member2_rol',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='member3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='member3_rol',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='project_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
